
#ifndef AGNETAOS_CONFIG_H
#define AGNETAOS_CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define AGNETAOS_TOTAL_INTERRUPTS 512
// 100MB heap size
#define AGNETAOS_HEAP_SIZE_BYTES 104857600
#define AGNETAOS_HEAP_BLOCK_SIZE 4096

#define AGNETAOS_HEAP_ADDRESS 0x01000000
#define AGNETAOS_HEAP_TABLE_ADDRESS 0x00007E00

#define AGNETAOS_SECTOR_SIZE 512

#define AGNETAOS_MAX_FILESYSTEMS 12
#define AGNETAOS_MAX_FILE_DESCRIPTORS 512

#define AGNETAOS_MAX_PATH 108
#define AGNETAOS_TOTAL_GDT_SEGMENTS 6

#define AGNEATOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define AGNETAOS_USER_PROGRAM_STACK_SIZE 1024 * 16

#define AGNEAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000

#define AGNEAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END AGNEAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - AGNETAOS_USER_PROGRAM_STACK_SIZE
#define USER_DATA_SEGMENT 0x23

#define USER_CODE_SEGMENT 0x1b
// A little bit small. Would increase it later on
#define AGNETAOS_MAX_PROGRAM_ALLOCATIONS 1024
#define AGNETAOS_MAX_PROCESSES 12

#define AGNETAOS_MAX_ISR80H_COMMANDS 1024
#define AGNETAOS_KEYBOARD_BUFFER_SIZE 1024

#define AGNETAOS_MAX_INTERRUPTS 512

#endif //AGNETAOS_CONFIG_H
